Repository silverfin/silverfin-vscode, pull requests merged in 2024-04, with the labels that each got.

#63 Bump silverfin-cli version to dependency with partner API updates
  CHANGELOG.md
  package-lock.json
  package.json
  src/lib/templateUpdater.ts
Labels: maintenance

#59 Bulk commands
  CHANGELOG.md
  package-lock.json
  package.json
  src/extension.ts
  src/lib/silverfinToolkit.ts
  src/lib/templateCommander.ts
Labels: enhancement

#64 Fix shared parts adding Quick Fix
  CHANGELOG.md
  package.json
  src/lib/diagnostics/sharedPartsVerifier.ts
Labels: bug
